# Generated by Django 4.2.9 on 2024-02-24 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinAgencyTeamAsClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_team_name', models.CharField(max_length=400)),
                ('current_unique_link', models.CharField(max_length=500)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CreateNewClientRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_title', models.CharField(max_length=300)),
                ('short_description', models.TextField()),
                ('client_request_body', models.TextField()),
                ('date_requested', models.DateTimeField(auto_now_add=True)),
                ('clients_assigned_agency_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency_client_side.joinagencyteamasclient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
