# Generated by Django 4.2.9 on 2024-02-24 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_client_side', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinagencyteamasclient',
            name='client_container_name',
            field=models.CharField(default='testing123', max_length=500),
        ),
    ]
