# Generated by Django 4.2.9 on 2024-02-25 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agency_client_side', '0002_joinagencyteamasclient_client_container_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateNewClientTaskClientSide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=300)),
                ('task_short_description', models.TextField()),
                ('task_due_date', models.CharField(max_length=200)),
                ('task_current_status', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('current_assigned_team_for_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency_client_side.joinagencyteamasclient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
