# Generated by Django 5.0.3 on 2024-04-07 06:19

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_client_side', '0003_createnewclienttaskclientside'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateNewClientFolderClientSide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_name', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('current_assigned_team_for_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency_client_side.joinagencyteamasclient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CreateNewClientFileClientSide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_file_name', models.CharField(max_length=300)),
                ('client_file', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('client_file_extension', models.CharField(blank=True, max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('current_assigned_team_for_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency_client_side.joinagencyteamasclient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('current_client_folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency_client_side.createnewclientfolderclientside')),
            ],
        ),
    ]
