# Generated by Django 5.0.3 on 2024-06-15 19:07

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateNewAgencyTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=500, unique=True)),
                ('client_assigned', models.CharField(blank=True, max_length=400, null=True)),
                ('team_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('unique_link', models.CharField(max_length=400)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CreateNewClientContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=400, unique=True)),
                ('client_description', models.TextField()),
                ('client_email', models.CharField(max_length=100)),
                ('client_budget', models.CharField(max_length=200)),
                ('date_assigned', models.DateTimeField(auto_now_add=True)),
                ('assigned_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency_side.createnewagencyteam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CreateNewClientFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_name', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('assigned_client_container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency_side.createnewclientcontainer')),
                ('assigned_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency_side.createnewagencyteam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CreateNewClientFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_file_name', models.CharField(max_length=300)),
                ('client_file', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('client_file_extension', models.CharField(blank=True, max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('assigned_client_container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency_side.createnewclientcontainer')),
                ('assigned_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency_side.createnewagencyteam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('assigned_client_folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency_side.createnewclientfolder')),
            ],
        ),
        migrations.CreateModel(
            name='CreateNewClientTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=300)),
                ('task_short_description', models.TextField()),
                ('task_due_date', models.CharField(max_length=200)),
                ('task_current_status', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('assigned_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency_side.createnewagencyteam')),
                ('current_client_container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency_side.createnewclientcontainer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JoinAgencyTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_unique_link', models.CharField(max_length=400)),
                ('date_joined_team', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
