# Generated by Django 5.0.3 on 2024-03-17 07:00

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency_side', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createnewagencyteam',
            name='team_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='createnewclientfile',
            name='client_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
